imu.mode:
  type: Integer
  note: 
      "Bit mask to enable IMU features:
    </br> Bit 1 - enable RawImu publisher,
    </br> Bit 2 - enable vibration metric publishing to RawImu.integration_interval,
    </br> Bit 3 - enable FFT acceleration publishing to RawImu.accelerometer_integral,
    </br> Bit 4 - enable FFT acceleration publishing to RawImu.rate_gyro_integral,
    </br> Bit 5 - enable synthetic data generation. Has priority over real readings,
    </br> Bit 6 - use FIFO for real data readings (sample rate = 100Hz, Bandwidth (gyro/accel) = 41/~44.8Hz). Has priority over register readings,
    </br> Bit 7 - use forward register adressing for data readings,
    </br> 15 - enable all publishers,
    Note: synthetic generation, FIFO and register readings should be used mutually exclusively."
  enum: PARAM_IMU_MODE_BITMASK
  flags: mutable
  default: 0
  min: 0
  max: 79

imu.pub_frequency:
  type: Integer
  note: Frequency of IMU publisher [Hz].
  enum: PARAM_IMU_PUB_FREQUENCY
  flags: mutable
  default: 1
  min: 0
  max: 400

imu.synthetic_frequency:
  type: Integer
  note: "Set frequency for synthetic oscilation generation on OX axis acceleration. 
    </br> If you want higher frequency then need to update FFT and other generation params to avoid aliasing."
  enum: SYNTHETIC_FREQ_GEN
  flags: mutable
  default: 8
  min: 1
  max: 128

imu.synthetic_amplitude:
  type: Integer
  note: "Set ampliture for synthetic oscilation generation on OX axis acceleration."
  enum: SYNTHETIC_AMPLITUDE
  flags: mutable
  default: 20
  min: 1
  max: 1000